import { kontrollsakResponseSchema, type KontrollsakResponse } from "~/saker/types.backend";
import { lagMockKontrollsak, lagMockSakUuid } from "~/saker/mock-uuid";

export type Avslutningsdatoer = Record<string, string>;

function lagSaksbehandlere(navn: string) {
  return {
    eier: null,
    deltMed: [],
    opprettetAv: { navIdent: navn.toUpperCase().replaceAll(" ", "_"), navn },
  };
}

function lagYtelse(id: string, type: string, dato: string) {
  return { id, type, periodeFra: dato, periodeTil: dato, belop: null };
}

const initialeMockStatistikkSaker = [
  {
    id: "S-101",
    personIdent: "10010199901",
    saksbehandlere: lagSaksbehandlere("Seksjon A"),
    status: "UFORDELT",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-101-ytelse-1", "Dagpenger", "2025-12-10")],
    merking: null,
    resultat: null,
    opprettet: "2025-12-10T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-102",
    personIdent: "10010299902",
    saksbehandlere: lagSaksbehandlere("Seksjon B"),
    status: "UFORDELT",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-102-ytelse-1", "Sykepenger", "2026-01-05")],
    merking: null,
    resultat: null,
    opprettet: "2026-01-05T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-201",
    personIdent: "20010199901",
    saksbehandlere: lagSaksbehandlere("Seksjon B"),
    status: "FORVALTNING",
    kategori: "FEILUTBETALING",
    kilde: "INTERN",
    misbruktype: ["Feil inntektsgrunnlag"],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-201-ytelse-1", "Sykepenger", "2025-11-15")],
    merking: null,
    resultat: {
      utredning: {
        id: "S-201-utredning-1",
        opprettet: "2025-11-20T00:00:00Z",
        resultat: "Avvik i a-ordningsdata",
      },
      forvaltning: {
        id: "S-201-forvaltning-1",
        dato: "2025-11-21",
        resultat: "Sendt til forvaltning",
      },
      strafferettsligVurdering: null,
    },
    opprettet: "2025-11-15T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-301",
    personIdent: "30010199901",
    saksbehandlere: lagSaksbehandlere("Seksjon A"),
    status: "UTREDES",
    kategori: "UDEFINERT",
    kilde: "INTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-301-ytelse-1", "Dagpenger", "2025-10-01")],
    merking: null,
    resultat: {
      utredning: {
        id: "S-301-utredning-1",
        opprettet: "2025-10-10T00:00:00Z",
        resultat: "Registeravvik under utredning",
      },
      forvaltning: null,
      strafferettsligVurdering: null,
    },
    opprettet: "2025-10-01T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-302",
    personIdent: "30010299902",
    saksbehandlere: lagSaksbehandlere("Seksjon B"),
    status: "UTREDES",
    kategori: "UDEFINERT",
    kilde: "INTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [
      lagYtelse("S-302-ytelse-1", "Sykepenger", "2025-10-15"),
      lagYtelse("S-302-ytelse-2", "Arbeidsavklaringspenger", "2025-10-15"),
    ],
    merking: null,
    resultat: null,
    opprettet: "2025-10-15T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-401",
    personIdent: "40010199901",
    saksbehandlere: lagSaksbehandlere("Seksjon A"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-401-ytelse-1", "Dagpenger", "2025-06-15")],
    merking: null,
    resultat: {
      utredning: {
        id: "S-401-utredning-1",
        opprettet: "2025-08-20T00:00:00Z",
        resultat: "Sak avsluttet etter grundig utredning",
      },
      forvaltning: null,
      strafferettsligVurdering: null,
    },
    opprettet: "2025-06-15T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-402",
    personIdent: "40010299902",
    saksbehandlere: lagSaksbehandlere("Seksjon B"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "INTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [
      lagYtelse("S-402-ytelse-1", "Sykepenger", "2025-07-01"),
      lagYtelse("S-402-ytelse-2", "Dagpenger", "2025-07-01"),
    ],
    merking: null,
    resultat: null,
    opprettet: "2025-07-01T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-403",
    personIdent: "40010399903",
    saksbehandlere: lagSaksbehandlere("Seksjon A"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-403-ytelse-1", "Foreldrepenger", "2025-08-10")],
    merking: null,
    resultat: null,
    opprettet: "2025-08-10T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-404",
    personIdent: "40010499904",
    saksbehandlere: lagSaksbehandlere("Seksjon C"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "INTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [
      lagYtelse("S-404-ytelse-1", "Uføretrygd", "2025-09-01"),
      lagYtelse("S-404-ytelse-2", "Arbeidsavklaringspenger", "2025-09-01"),
    ],
    merking: null,
    resultat: null,
    opprettet: "2025-09-01T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-405",
    personIdent: "40010599905",
    saksbehandlere: lagSaksbehandlere("Seksjon D"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-405-ytelse-1", "Pleiepenger", "2025-09-20")],
    merking: null,
    resultat: null,
    opprettet: "2025-09-20T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-406",
    personIdent: "40010699906",
    saksbehandlere: lagSaksbehandlere("Seksjon E"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-406-ytelse-1", "Kontantstøtte", "2025-10-10")],
    merking: null,
    resultat: null,
    opprettet: "2025-10-10T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-407",
    personIdent: "40010799907",
    saksbehandlere: lagSaksbehandlere("Seksjon A"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [
      lagYtelse("S-407-ytelse-1", "Dagpenger", "2025-11-05"),
      lagYtelse("S-407-ytelse-2", "Overgangsstønad", "2025-11-05"),
    ],
    merking: null,
    resultat: null,
    opprettet: "2025-11-05T00:00:00Z",
    oppdatert: null,
  },
  {
    id: "S-408",
    personIdent: "40010899908",
    saksbehandlere: lagSaksbehandlere("Seksjon B"),
    status: "AVSLUTTET",
    kategori: "UDEFINERT",
    kilde: "EKSTERN",
    misbruktype: [],
    prioritet: "NORMAL",
    ytelser: [lagYtelse("S-408-ytelse-1", "Sykepenger", "2025-12-01")],
    merking: null,
    resultat: null,
    opprettet: "2025-12-01T00:00:00Z",
    oppdatert: null,
  },
] satisfies KontrollsakResponse[];

function lagMockStatistikkSaker() {
  return initialeMockStatistikkSaker.map((sak) =>
    kontrollsakResponseSchema.parse(lagMockKontrollsak(sak, 3)),
  );
}

export const mockStatistikkSaker: KontrollsakResponse[] = lagMockStatistikkSaker();

export const mockAvslutningsdatoer: Avslutningsdatoer = {
  [lagMockSakUuid("S-401", 3)]: "2025-08-20",
  [lagMockSakUuid("S-402", 3)]: "2025-08-15",
  [lagMockSakUuid("S-403", 3)]: "2025-09-18",
  [lagMockSakUuid("S-404", 3)]: "2025-12-10",
  [lagMockSakUuid("S-405", 3)]: "2025-10-28",
  [lagMockSakUuid("S-406", 3)]: "2025-10-18",
  [lagMockSakUuid("S-407", 3)]: "2025-12-20",
  [lagMockSakUuid("S-408", 3)]: "2025-12-22",
};
