import { type Sak, sakSchema } from "~/saker/typer";

const rådata: Sak[] = [
  {
    id: "1",
    datoInnmeldt: "2026-01-15",
    kilde: "telefon",
    notat: "Tipser melder om mulig feil utbetaling av dagpenger.",
    fødselsnummer: "12345678901",
    ytelser: ["Dagpenger"],
    status: "tips mottatt",
    seksjon: "Seksjon A",
    fraDato: "2025-06-01",
    tilDato: "2025-12-31",
    avdeling: "Kontroll Øst",
    kategori: "Feilutbetaling",
    tags: ["dagpenger", "feilutbetaling"],
    kontaktinformasjon: {
      navn: "Ola Nordmann",
      telefon: "99887766",
      epost: "ola@example.com",
      anonymt: false,
    },
    beskrivelse: "Tipser melder om mulig feil utbetaling av dagpenger.",
  },
  {
    id: "2",
    datoInnmeldt: "2026-01-20",
    kilde: "registersamkjøring",
    notat: "Avvik mellom arbeidsgiver- og a-ordningsdata.",
    fødselsnummer: "23456789012",
    ytelser: ["Sykepenger", "Arbeidsavklaringspenger"],
    status: "tips avklart",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    kategori: "Registeravvik",
    tags: ["registersamkjøring", "a-ordning"],
    beskrivelse: "Avvik mellom arbeidsgiver- og a-ordningsdata.",
  },
  {
    id: "3",
    datoInnmeldt: "2026-02-01",
    kilde: "saksbehandler",
    notat: "Saksbehandler har avdekket mulig dobbeltutbetaling.",
    fødselsnummer: "34567890123",
    ytelser: ["Foreldrepenger"],
    status: "under utredning",
    seksjon: "Seksjon A",
    fraDato: "2025-09-01",
    tilDato: "2026-03-01",
    avdeling: "Kontroll Øst",
    kategori: "Dobbeltutbetaling",
    tags: ["foreldrepenger", "dobbeltutbetaling"],
    kontaktinformasjon: {
      navn: "Kari Saksbehandler",
      telefon: "98765432",
      epost: "kari@nav.no",
      anonymt: false,
    },
    beskrivelse: "Saksbehandler har avdekket mulig dobbeltutbetaling.",
  },
  {
    id: "4",
    datoInnmeldt: "2026-02-10",
    kilde: "brev",
    notat: "Mottatt anonymt tips per brev.",
    fødselsnummer: "45678901234",
    ytelser: ["Uføretrygd"],
    status: "tips mottatt",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Nord",
    kategori: "Anonymt tips",
    tags: ["uføretrygd", "anonymt"],
    kontaktinformasjon: {
      anonymt: true,
    },
    beskrivelse: "Mottatt anonymt tips per brev.",
  },
  {
    id: "5",
    datoInnmeldt: "2026-02-18",
    kilde: "epost",
    notat: "Epost fra ekstern kilde om mulig misbruk av pleiepenger.",
    fødselsnummer: "56789012345",
    ytelser: ["Pleiepenger"],
    status: "avsluttet",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Sør",
    kategori: "Misbruk",
    tags: ["pleiepenger"],
    kontaktinformasjon: {
      navn: "Per Tipser",
      epost: "per@example.com",
      anonymt: false,
    },
    beskrivelse: "Epost fra ekstern kilde om mulig misbruk av pleiepenger.",
  },
  {
    id: "6",
    datoInnmeldt: "2026-02-22",
    kilde: "annet",
    notat: "Flagget via intern kontroll.",
    fødselsnummer: "67890123456",
    ytelser: ["Dagpenger", "Sykepenger"],
    status: "tips mottatt",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    kategori: "Internkontroll",
    tags: ["dagpenger", "sykepenger", "internkontroll"],
    beskrivelse: "Flagget via intern kontroll.",
  },
];

export const mockSaker: Sak[] = rådata.map((sak) => sakSchema.parse(sak));

export const mockAvdelinger = [
  "Kontroll Øst",
  "Kontroll Vest",
  "Kontroll Nord",
  "Kontroll Sør",
  "Kontroll Midt",
];

export const mockKategorier = [
  "Feilutbetaling",
  "Dobbeltutbetaling",
  "Registeravvik",
  "Misbruk",
  "Anonymt tips",
  "Internkontroll",
  "Annet",
];

export const mockTags = [
  "dagpenger",
  "sykepenger",
  "foreldrepenger",
  "pleiepenger",
  "uføretrygd",
  "arbeidsavklaringspenger",
  "feilutbetaling",
  "dobbeltutbetaling",
  "registersamkjøring",
  "a-ordning",
  "anonymt",
  "internkontroll",
];

export const mockYtelser = [
  "Dagpenger",
  "Sykepenger",
  "Foreldrepenger",
  "Pleiepenger",
  "Uføretrygd",
  "Arbeidsavklaringspenger",
  "Overgangsstønad",
  "Kontantstøtte",
];
