export const mockSaksbehandlere = [
  "Ada Larsen",
  "Aksel Johansen",
  "Alexander Haugen",
  "Amalie Olsen",
  "Andreas Berg",
  "Anne Kristiansen",
  "Arne Dahl",
  "Astrid Halvorsen",
  "Berit Solberg",
  "Bjørn Eriksen",
  "Camilla Arnesen",
  "Christian Moe",
  "Dag Henriksen",
  "Eli Bakken",
  "Erik Strand",
  "Eva Holmberg",
  "Frida Nilsen",
  "Geir Martinsen",
  "Grete Pedersen",
  "Hans Petter Lund",
  "Hege Svendsen",
  "Henrik Andersen",
  "Ida Thorsen",
  "Ingrid Aas",
  "Jan Ivar Holm",
  "Jonas Berntsen",
  "Julie Hauge",
  "Kari Nordmann",
  "Karl Fredrik Moen",
  "Katrine Vold",
  "Kristin Bjerke",
  "Lars Hansen",
  "Linda Fossheim",
  "Magne Sørensen",
  "Marit Nygård",
  "Martin Ruud",
  "Mette Johannessen",
  "Morten Knutsen",
  "Nina Hagen",
  "Nora Bjørnstad",
  "Ola Nordmann",
  "Ole Kristian Lie",
  "Pål Stensrud",
  "Per Arne Haugen",
  "Ragnhild Tangen",
  "Rune Brekke",
  "Silje Ødegård",
  "Simen Åsberg",
  "Solveig Engen",
  "Stian Wold",
  "Terje Fjellstad",
  "Thomas Haugland",
  "Tonje Vikene",
  "Tor Magnus Lien",
  "Trond Gulbrandsen",
  "Turid Iversen",
  "Vegard Ness",
  "Vibeke Røed",
  "Vidar Skogen",
  "Wenche Brekken",
];
