import { type Sak, sakSchema } from "~/saker/typer";

const rådata: Sak[] = [
  {
    id: "101",
    datoInnmeldt: "2026-01-10",
    kilde: "saksbehandler",
    notat: "Mulig dobbeltutbetaling av dagpenger. Kontrollert mot A-ordning.",
    fødselsnummer: "11223344556",
    ytelser: ["Dagpenger"],
    status: "under utredning",
    seksjon: "Seksjon A",
    fraDato: "2025-08-01",
    tilDato: "2026-01-31",
    avdeling: "Kontroll Øst",
    kategori: "Dobbeltutbetaling",
    tags: ["dagpenger", "dobbeltutbetaling"],
    beskrivelse: "Mulig dobbeltutbetaling av dagpenger. Kontrollert mot A-ordning.",
  },
  {
    id: "102",
    datoInnmeldt: "2026-02-05",
    kilde: "registersamkjøring",
    notat: "Registersamkjøring avdekket avvik i sykepengegrunnlag.",
    fødselsnummer: "22334455667",
    ytelser: ["Sykepenger"],
    status: "tips avklart",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    kategori: "Registeravvik",
    tags: ["sykepenger", "registersamkjøring"],
    beskrivelse: "Registersamkjøring avdekket avvik i sykepengegrunnlag.",
  },
  {
    id: "103",
    datoInnmeldt: "2026-02-20",
    kilde: "telefon",
    notat: "Tips om mulig misbruk av foreldrepenger. Oppfølging pågår.",
    fødselsnummer: "33445566778",
    ytelser: ["Foreldrepenger"],
    status: "tips mottatt",
    seksjon: "Seksjon A",
    fraDato: "2025-11-01",
    avdeling: "Kontroll Øst",
    kategori: "Misbruk",
    tags: ["foreldrepenger"],
    kontaktinformasjon: {
      navn: "Per Hansen",
      telefon: "90123456",
      anonymt: false,
    },
    beskrivelse: "Tips om mulig misbruk av foreldrepenger. Oppfølging pågår.",
  },
  {
    id: "104",
    datoInnmeldt: "2026-03-01",
    kilde: "epost",
    notat: "Mottatt henvendelse om feilutbetaling av arbeidsavklaringspenger.",
    fødselsnummer: "44556677889",
    ytelser: ["Arbeidsavklaringspenger", "Sykepenger"],
    status: "tips mottatt",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Sør",
    kategori: "Feilutbetaling",
    tags: ["arbeidsavklaringspenger", "sykepenger", "feilutbetaling"],
    kontaktinformasjon: {
      epost: "tip@example.com",
      anonymt: false,
    },
    beskrivelse: "Mottatt henvendelse om feilutbetaling av arbeidsavklaringspenger.",
  },
];

export const mockMineSaker: Sak[] = rådata.map((sak) => sakSchema.parse(sak));
