import { type Sak, sakSchema } from "~/saker/typer";

const rådata: Sak[] = [
  {
    id: "101",
    datoInnmeldt: "2026-01-10",
    kilde: "saksbehandler",
    notat: "Mulig dobbeltutbetaling av dagpenger. Kontrollert mot A-ordning.",
    fødselsnummer: "11223344556",
    ytelser: ["Dagpenger"],
    status: "under utredning",
    seksjon: "Seksjon A",
    fraDato: "2025-08-01",
    tilDato: "2026-01-31",
    avdeling: "Kontroll Øst",
    kategori: "Dobbeltutbetaling",
    tags: ["dagpenger", "dobbeltutbetaling"],
    beskrivelse: "Mulig dobbeltutbetaling av dagpenger. Kontrollert mot A-ordning.",
  },
  {
    id: "102",
    datoInnmeldt: "2026-02-05",
    kilde: "registersamkjøring",
    notat: "Registersamkjøring avdekket avvik i sykepengegrunnlag.",
    fødselsnummer: "22334455667",
    ytelser: ["Sykepenger"],
    status: "tips avklart",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    kategori: "Registeravvik",
    tags: ["sykepenger", "registersamkjøring"],
    beskrivelse: "Registersamkjøring avdekket avvik i sykepengegrunnlag.",
  },
  {
    id: "103",
    datoInnmeldt: "2026-02-20",
    kilde: "telefon",
    notat: "Tips om mulig misbruk av foreldrepenger. Oppfølging pågår.",
    fødselsnummer: "33445566778",
    ytelser: ["Foreldrepenger"],
    status: "tips mottatt",
    seksjon: "Seksjon A",
    fraDato: "2025-11-01",
    avdeling: "Kontroll Øst",
    kategori: "Misbruk",
    tags: ["foreldrepenger"],
    kontaktinformasjon: {
      navn: "Per Hansen",
      telefon: "90123456",
      anonymt: false,
    },
    beskrivelse: "Tips om mulig misbruk av foreldrepenger. Oppfølging pågår.",
  },
  {
    id: "104",
    datoInnmeldt: "2026-03-01",
    kilde: "epost",
    notat: "Mottatt henvendelse om feilutbetaling av arbeidsavklaringspenger.",
    fødselsnummer: "44556677889",
    ytelser: ["Arbeidsavklaringspenger", "Sykepenger"],
    status: "tips mottatt",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Sør",
    kategori: "Feilutbetaling",
    tags: ["arbeidsavklaringspenger", "sykepenger", "feilutbetaling"],
    kontaktinformasjon: {
      epost: "tip@example.com",
      anonymt: false,
    },
    beskrivelse: "Mottatt henvendelse om feilutbetaling av arbeidsavklaringspenger.",
  },
  {
    id: "105",
    datoInnmeldt: "2026-03-05",
    kilde: "registersamkjøring",
    notat: "Tips avklart etter kontroll av sykepengegrunnlag.",
    fødselsnummer: "55667788990",
    ytelser: ["Sykepenger"],
    status: "tips avklart",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    kategori: "Registeravvik",
    tags: ["sykepenger", "tips-avklart"],
    beskrivelse: "Tips avklart etter kontroll av sykepengegrunnlag.",
  },
  {
    id: "106",
    datoInnmeldt: "2026-03-06",
    kilde: "telefon",
    notat: "Sak videresendt til NAY/NFP for videre behandling.",
    fødselsnummer: "66778899001",
    ytelser: ["Dagpenger"],
    status: "videresendt til nay/nfp",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    kategori: "Videresending",
    tags: ["dagpenger", "nay-nfp"],
    beskrivelse: "Sak videresendt til NAY/NFP for videre behandling.",
  },
  {
    id: "107",
    datoInnmeldt: "2026-03-08",
    kilde: "epost",
    notat: "Henlagt tips etter vurdering av dokumentasjon.",
    fødselsnummer: "77889900112",
    ytelser: ["Foreldrepenger"],
    status: "henlagt",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Sør",
    kategori: "Henlagt tips",
    tags: ["foreldrepenger", "henlagt", "tips"],
    beskrivelse: "Henlagt tips etter vurdering av dokumentasjon.",
  },
  {
    id: "108",
    datoInnmeldt: "2026-03-10",
    kilde: "saksbehandler",
    notat: "Sak under utredning etter intern oppfølging.",
    fødselsnummer: "88990011223",
    ytelser: ["Arbeidsavklaringspenger"],
    status: "under utredning",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    kategori: "Utredning",
    tags: ["arbeidsavklaringspenger", "utredning"],
    beskrivelse: "Sak under utredning etter intern oppfølging.",
  },
  {
    id: "109",
    datoInnmeldt: "2026-03-12",
    kilde: "brev",
    notat: "Sak avsluttet etter ferdig behandling.",
    fødselsnummer: "99001122334",
    ytelser: ["Dagpenger", "Sykepenger"],
    status: "avsluttet",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    kategori: "Avsluttet sak",
    tags: ["avsluttet"],
    beskrivelse: "Sak avsluttet etter ferdig behandling.",
  },
  {
    id: "110",
    datoInnmeldt: "2026-03-14",
    kilde: "saksbehandler",
    notat: "Henlagt sak etter intern kontroll.",
    fødselsnummer: "00112233445",
    ytelser: ["Pleiepenger"],
    status: "henlagt",
    seksjon: "Seksjon D",
    avdeling: "Kontroll Midt",
    kategori: "Henlagt sak",
    tags: ["henlagt"],
    beskrivelse: "Henlagt sak etter intern kontroll.",
  },
];

export let mockMineSaker: Sak[] = rådata.map((sak) => sakSchema.parse(sak));

export const mockMineSakerAvslutningsdatoer = {
  "107": "2026-03-12",
  "109": "2026-03-16",
  "110": "2026-03-18",
};

export const mockMineSakerTidligereTipsSakIder = ["107"];

/** Tilbakestill mine mock-saker til opprinnelig tilstand */
export function resetMockMineSaker() {
  mockMineSaker = rådata.map((sak) => sakSchema.parse(sak));
}
