import type { MigreringKandidat } from "./types";

// Syntetiske visningseksempler uten reelle FNR. Dekker alle 6 kategorier iht 2.a frosset kontrakt.
function utredningsfelter(
  utredres: string | null,
  fvres: string | null = null,
  ferdigdato = false,
  prosjektenhet: string | null = null,
): MigreringKandidat["kildefelter"] {
  return [
    { felt: "TIPSAVKL", verdi: "Utredes" },
    { felt: "UTREDRES", verdi: utredres },
    { felt: "FVRES", verdi: fvres },
    { felt: "FVDATO", verdi: fvres ? "2024-03-01" : null },
    { felt: "FERDIGDATO", verdi: ferdigdato ? "2024-03-15" : null },
    { felt: "PROSJEKTENHET", verdi: prosjektenhet },
  ];
}

function svFelter(
  svres: string | null,
  poldomres: string | null = null,
  poldomdato: string | null = null,
  svdato: string | null = "2023-05-10",
  prosjektident: string | null = null,
): MigreringKandidat["kildefelter"] {
  return [
    { felt: "SVRES", verdi: svres },
    { felt: "SVDATO", verdi: svdato },
    { felt: "POLDOMRES", verdi: poldomres },
    { felt: "POLDOMDATO", verdi: poldomdato },
    { felt: "PROSJEKTIDENT", verdi: prosjektident },
  ];
}

function registerFelter(
  tabell: string,
  resultat: string = "UNDER ARBEID",
  saksbehandler: string | null = null,
): MigreringKandidat["kildefelter"] {
  return [
    { felt: "TABELL", verdi: tabell },
    { felt: "RESULTAT", verdi: resultat },
    { felt: "SAKSBEHANDLER", verdi: saksbehandler },
  ];
}

export function hentMockMigreringKandidater(navIdent: string): MigreringKandidat[] {
  return [
    // 1. TIPS_RESTANSE
    {
      kandidatId: "UTREDNING:100245",
      kilde: "UTREDNING",
      legacyKilde: "UTREDNING",
      pid: "100245",
      legacyPid: "100245",
      kategori: "TIPS_RESTANSE",
      navn: "Ada Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "12345678901",
      enhet: "4812",
      vurdering: "MULIG_KANDIDAT",
      ekskluderFraStatistikk: false,
      referansedato: "2023-01-15",
      referansedatoFelt: "TIPSINNDATO",
      fase: "Utredning uten resultat",
      begrunnelse: "TIPSINNDATO er satt og UTREDRES mangler. Oppfyller regelen for tipsrestanse.",
      kildefelter: utredningsfelter(null),
      alleredeMigrertTilKontrollsakId: 1181,
    },
    {
      kandidatId: "UTREDNING:100310",
      kilde: "UTREDNING",
      legacyKilde: "UTREDNING",
      pid: "100310",
      legacyPid: "100310",
      kategori: "TIPS_RESTANSE",
      navn: "Bente Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "23456789012",
      enhet: "4812",
      vurdering: "MA_AVKLARES",
      ekskluderFraStatistikk: false,
      referansedato: "2023-02-20",
      referansedatoFelt: "TIPSINNDATO",
      fase: "Henlagt under avklaring",
      begrunnelse: "TIPSAVKL er 'Henlagt', men UTREDRES mangler. Avvik som må avklares.",
      kildefelter: [
        { felt: "TIPSAVKL", verdi: "Henlagt" },
        { felt: "UTREDRES", verdi: null },
        { felt: "FERDIGDATO", verdi: "2023-03-01" },
      ],
    },

    // 2. TIPS_VENTER_RESULTAT
    {
      kandidatId: "UTREDNING:100388",
      kilde: "UTREDNING",
      legacyKilde: "UTREDNING",
      pid: "100388",
      legacyPid: "100388",
      kategori: "TIPS_VENTER_RESULTAT",
      navn: "Carl Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "34567890123",
      enhet: "4812",
      vurdering: "MULIG_KANDIDAT",
      ekskluderFraStatistikk: false,
      referansedato: "2022-11-05",
      referansedatoFelt: "TIPSINNDATO",
      fase: "Venter på resultat fra Nay/NFP",
      begrunnelse: "REV. STRAFFESAK og FVRES er tom. Verken Spaniakontoret eller Kontroll analyse.",
      kildefelter: utredningsfelter("REV. STRAFFESAK"),
    },
    {
      kandidatId: "UTREDNING:100412",
      kilde: "UTREDNING",
      legacyKilde: "UTREDNING",
      pid: "100412",
      legacyPid: "100412",
      kategori: "TIPS_VENTER_RESULTAT",
      navn: "Dag Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "45678901234",
      enhet: "4812",
      vurdering: "MA_AVKLARES",
      ekskluderFraStatistikk: false,
      referansedato: "2022-09-12",
      referansedatoFelt: "TIPSINNDATO",
      fase: "Revisjon ikke straffesak",
      begrunnelse: "REV. IKKE STRAFFESAK uten forvaltningsresultat.",
      kildefelter: utredningsfelter("REV. IKKE STRAFFESAK"),
    },

    // 3. SV_RESTANSE
    {
      kandidatId: "SV:100245",
      kilde: "SV",
      legacyKilde: "SV",
      pid: "100245",
      legacyPid: "100245",
      kategori: "SV_RESTANSE",
      navn: "Ester Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "56789012345",
      enhet: "4812",
      vurdering: "MULIG_KANDIDAT",
      ekskluderFraStatistikk: false,
      referansedato: "2023-08-01",
      referansedatoFelt: "SVMOTTATT",
      fase: "Straffesak restanse",
      begrunnelse: "SVMOTTATT er satt og SVRES er tom. Kildepost holdes adskilt fra utredning.",
      kildefelter: [
        { felt: "SVMOTTATT", verdi: "2023-08-01" },
        { felt: "SVRES", verdi: null },
      ],
    },
    {
      kandidatId: "SV:100634",
      kilde: "SV",
      legacyKilde: "SV",
      pid: "100634",
      legacyPid: "100634",
      kategori: "SV_RESTANSE",
      navn: "Geir Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "67890123456",
      enhet: "4812",
      vurdering: "MA_AVKLARES",
      ekskluderFraStatistikk: false,
      referansedato: "2022-04-10",
      referansedatoFelt: "SVMOTTATT",
      fase: "Dato uten resultat i SV",
      begrunnelse: "SVMOTTATT og SVDATO er satt, men SVRES mangler. Må avklares.",
      kildefelter: [
        { felt: "SVMOTTATT", verdi: "2022-04-10" },
        { felt: "SVDATO", verdi: "2022-05-01" },
        { felt: "SVRES", verdi: null },
      ],
    },

    // 4. SV_VENTER_RESULTAT
    {
      kandidatId: "SV:100501",
      kilde: "SV",
      legacyKilde: "SV",
      pid: "100501",
      legacyPid: "100501",
      kategori: "SV_VENTER_RESULTAT",
      navn: "Fie Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "78901234567",
      enhet: "4812",
      vurdering: "MULIG_KANDIDAT",
      ekskluderFraStatistikk: false,
      referansedato: "2023-05-10",
      referansedatoFelt: "SVDATO",
      fase: "Anmeldt politi uten resultat",
      begrunnelse:
        "Anmeldt med SVDATO nyere enn 2020-01-01 og POLDOMDATO er tom. Prosjektident er ikke KA.",
      kildefelter: svFelter("Anmeldt", null, null, "2023-05-10"),
    },
    {
      kandidatId: "SV:100502",
      kilde: "SV",
      legacyKilde: "SV",
      pid: "100502",
      legacyPid: "100502",
      kategori: "SV_VENTER_RESULTAT",
      navn: "Arbeidsgiver Anmeldt Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "89012345678",
      enhet: "4812",
      vurdering: "MULIG_KANDIDAT",
      ekskluderFraStatistikk: true,
      referansedato: "2023-06-15",
      referansedatoFelt: "SVDATO",
      fase: "Anmeldt arbeidsgiver",
      begrunnelse: "SVRES = 'Anm. Agiver'. Holdes utenfor offisiell trygdemisbruksstatistikk.",
      kildefelter: svFelter("Anm. Agiver", null, null, "2023-06-15"),
    },
    {
      kandidatId: "SV:100503",
      kilde: "SV",
      legacyKilde: "SV",
      pid: "100503",
      legacyPid: "100503",
      kategori: "SV_VENTER_RESULTAT",
      navn: "Tom Dato Eksempel",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "90123456789",
      enhet: "4812",
      vurdering: "MA_AVKLARES",
      ekskluderFraStatistikk: false,
      referansedato: null,
      referansedatoFelt: "SVDATO",
      fase: "Venter resultat uten referansedato",
      begrunnelse: "SV_VENTER_RESULTAT hvor SVDATO mangler. Må avklares.",
      kildefelter: svFelter("Anmeldt", null, null, null),
    },

    // 5. REGISTER_DAGPENGER
    {
      kandidatId: "NKA_DAGPENGER:700101",
      kilde: "NKA_DAGPENGER",
      legacyKilde: "NKA_DAGPENGER",
      pid: "700101",
      legacyPid: "700101",
      kategori: "REGISTER_DAGPENGER",
      navn: "Dagny Dagpenger",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "01234567890",
      enhet: "4812",
      vurdering: "MULIG_KANDIDAT",
      ekskluderFraStatistikk: false,
      referansedato: null,
      referansedatoFelt: null,
      fase: "Registerkontroll dagpenger under arbeid",
      begrunnelse: "NKA_KONTROLL med RESULTAT = 'UNDER ARBEID'.",
      kildefelter: registerFelter("NKA_KONTROLL", "UNDER ARBEID", navIdent),
    },

    // 6. REGISTER_AAP
    {
      kandidatId: "NKA_AAP:800202",
      kilde: "NKA_AAP",
      legacyKilde: "NKA_AAP",
      pid: "800202",
      legacyPid: "800202",
      kategori: "REGISTER_AAP",
      navn: "Arne Arbeidsavklaring",
      ansvar: { type: "BEKREFTET", navIdent },
      personIdent: "11223344556",
      enhet: "4812",
      vurdering: "MULIG_KANDIDAT",
      ekskluderFraStatistikk: false,
      referansedato: null,
      referansedatoFelt: null,
      fase: "Registerkontroll AAP under arbeid",
      begrunnelse:
        "NKA_KONTROLL_AAP med RESULTAT = 'UNDER ARBEID'. Søkeloggtreff for saksbehandler.",
      kildefelter: registerFelter("NKA_KONTROLL_AAP", "UNDER ARBEID", null),
    },
  ];
}
