import { type Sak, sakSchema } from "~/saker/typer";

/** Avslutningsdatoer for avsluttede/henlagte saker (sakId → ISO-dato) */
export type Avslutningsdatoer = Record<string, string>;

const ytelser = [
  "Dagpenger",
  "Sykepenger",
  "Foreldrepenger",
  "Pleiepenger",
  "Uføretrygd",
  "Arbeidsavklaringspenger",
  "Overgangsstønad",
  "Kontantstøtte",
];

const seksjoner = ["Seksjon A", "Seksjon B", "Seksjon C", "Seksjon D", "Seksjon E"];

const kilder = [
  "telefon",
  "epost",
  "brev",
  "registersamkjøring",
  "saksbehandler",
  "publikum",
  "annet",
] as const;

const rådata: Sak[] = [
  // Tips mottatt (6 stk)
  {
    id: "S-101",
    datoInnmeldt: "2025-12-10",
    kilde: "telefon",
    notat: "Tips om mulig feilutbetaling",
    fødselsnummer: "10010199901",
    ytelser: ["Dagpenger"],
    status: "tips mottatt",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-102",
    datoInnmeldt: "2026-01-05",
    kilde: "epost",
    notat: "Melding om mulig trygdemisbruk",
    fødselsnummer: "10010299902",
    ytelser: ["Sykepenger", "Dagpenger"],
    status: "tips mottatt",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    tags: [],
  },
  {
    id: "S-103",
    datoInnmeldt: "2026-01-18",
    kilde: "brev",
    notat: "Anonymt brev om mulig misbruk",
    fødselsnummer: "10010399903",
    ytelser: ["Uføretrygd"],
    status: "tips mottatt",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Nord",
    tags: [],
  },
  {
    id: "S-104",
    datoInnmeldt: "2026-02-01",
    kilde: "publikum",
    notat: "Tips fra publikum",
    fødselsnummer: "10010499904",
    ytelser: ["Foreldrepenger"],
    status: "tips mottatt",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-105",
    datoInnmeldt: "2026-02-20",
    kilde: "telefon",
    notat: "Telefontips om dobbeltutbetaling",
    fødselsnummer: "10010599905",
    ytelser: ["Arbeidsavklaringspenger"],
    status: "tips mottatt",
    seksjon: "Seksjon D",
    avdeling: "Kontroll Sør",
    tags: [],
  },
  {
    id: "S-106",
    datoInnmeldt: "2026-03-01",
    kilde: "annet",
    notat: "Internkontroll avdekket avvik",
    fødselsnummer: "10010699906",
    ytelser: ["Dagpenger", "Sykepenger"],
    status: "tips mottatt",
    seksjon: "Seksjon E",
    avdeling: "Kontroll Midt",
    tags: [],
  },
  // Tips avklart (5 stk)
  {
    id: "S-201",
    datoInnmeldt: "2025-11-15",
    kilde: "registersamkjøring",
    notat: "Avvik i a-ordningsdata",
    fødselsnummer: "20010199901",
    ytelser: ["Sykepenger"],
    status: "tips avklart",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    tags: [],
  },
  {
    id: "S-202",
    datoInnmeldt: "2025-12-01",
    kilde: "saksbehandler",
    notat: "Saksbehandler meldte fra om mulig feil",
    fødselsnummer: "20010299902",
    ytelser: ["Foreldrepenger", "Kontantstøtte"],
    status: "tips avklart",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-203",
    datoInnmeldt: "2025-12-20",
    kilde: "telefon",
    notat: "Tips avklart etter samtale",
    fødselsnummer: "20010399903",
    ytelser: ["Pleiepenger"],
    status: "tips avklart",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Nord",
    tags: [],
  },
  {
    id: "S-204",
    datoInnmeldt: "2026-01-10",
    kilde: "epost",
    notat: "Epost-tips avklart",
    fødselsnummer: "20010499904",
    ytelser: ["Overgangsstønad"],
    status: "tips avklart",
    seksjon: "Seksjon D",
    avdeling: "Kontroll Sør",
    tags: [],
  },
  {
    id: "S-205",
    datoInnmeldt: "2026-01-25",
    kilde: "brev",
    notat: "Brevtips avklart",
    fødselsnummer: "20010599905",
    ytelser: ["Dagpenger", "Arbeidsavklaringspenger"],
    status: "tips avklart",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  // Under utredning (8 stk)
  {
    id: "S-301",
    datoInnmeldt: "2025-10-01",
    kilde: "registersamkjøring",
    notat: "Registeravvik under utredning",
    fødselsnummer: "30010199901",
    ytelser: ["Dagpenger"],
    status: "under utredning",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-302",
    datoInnmeldt: "2025-10-15",
    kilde: "saksbehandler",
    notat: "Utredning av mulig dobbeltutbetaling",
    fødselsnummer: "30010299902",
    ytelser: ["Sykepenger", "Arbeidsavklaringspenger"],
    status: "under utredning",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    tags: [],
  },
  {
    id: "S-303",
    datoInnmeldt: "2025-11-01",
    kilde: "telefon",
    notat: "Kompleks sak under utredning",
    fødselsnummer: "30010399903",
    ytelser: ["Foreldrepenger", "Pleiepenger", "Kontantstøtte"],
    status: "under utredning",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Nord",
    tags: [],
  },
  {
    id: "S-304",
    datoInnmeldt: "2025-11-20",
    kilde: "epost",
    notat: "Utredning basert på epost-tips",
    fødselsnummer: "30010499904",
    ytelser: ["Uføretrygd"],
    status: "under utredning",
    seksjon: "Seksjon D",
    avdeling: "Kontroll Sør",
    tags: [],
  },
  {
    id: "S-305",
    datoInnmeldt: "2025-12-05",
    kilde: "publikum",
    notat: "Tips fra publikum, nå under utredning",
    fødselsnummer: "30010599905",
    ytelser: ["Dagpenger", "Sykepenger"],
    status: "under utredning",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-306",
    datoInnmeldt: "2025-12-15",
    kilde: "brev",
    notat: "Brevsak under utredning",
    fødselsnummer: "30010699906",
    ytelser: ["Overgangsstønad"],
    status: "under utredning",
    seksjon: "Seksjon E",
    avdeling: "Kontroll Midt",
    tags: [],
  },
  {
    id: "S-307",
    datoInnmeldt: "2026-01-02",
    kilde: "registersamkjøring",
    notat: "Nytt registeravvik oppdaget",
    fødselsnummer: "30010799907",
    ytelser: ["Sykepenger"],
    status: "under utredning",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    tags: [],
  },
  {
    id: "S-308",
    datoInnmeldt: "2026-01-15",
    kilde: "saksbehandler",
    notat: "Saksbehandler-initiert utredning",
    fødselsnummer: "30010899908",
    ytelser: ["Pleiepenger", "Foreldrepenger"],
    status: "under utredning",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Nord",
    tags: [],
  },
  // Avsluttet (8 stk) – med varierende behandlingstid
  {
    id: "S-401",
    datoInnmeldt: "2025-06-15",
    kilde: "telefon",
    notat: "Sak avsluttet etter grundig utredning",
    fødselsnummer: "40010199901",
    ytelser: ["Dagpenger"],
    status: "avsluttet",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-402",
    datoInnmeldt: "2025-07-01",
    kilde: "registersamkjøring",
    notat: "Registeravvik avklart og avsluttet",
    fødselsnummer: "40010299902",
    ytelser: ["Sykepenger", "Dagpenger"],
    status: "avsluttet",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    tags: [],
  },
  {
    id: "S-403",
    datoInnmeldt: "2025-08-10",
    kilde: "epost",
    notat: "Epost-sak ferdig behandlet",
    fødselsnummer: "40010399903",
    ytelser: ["Foreldrepenger"],
    status: "avsluttet",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-404",
    datoInnmeldt: "2025-09-01",
    kilde: "saksbehandler",
    notat: "Sak avsluttet – ingen feil funnet",
    fødselsnummer: "40010499904",
    ytelser: ["Uføretrygd", "Arbeidsavklaringspenger"],
    status: "avsluttet",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Nord",
    tags: [],
  },
  {
    id: "S-405",
    datoInnmeldt: "2025-09-20",
    kilde: "brev",
    notat: "Brevsak avsluttet",
    fødselsnummer: "40010599905",
    ytelser: ["Pleiepenger"],
    status: "avsluttet",
    seksjon: "Seksjon D",
    avdeling: "Kontroll Sør",
    tags: [],
  },
  {
    id: "S-406",
    datoInnmeldt: "2025-10-10",
    kilde: "telefon",
    notat: "Raskt avsluttet telefontips",
    fødselsnummer: "40010699906",
    ytelser: ["Kontantstøtte"],
    status: "avsluttet",
    seksjon: "Seksjon E",
    avdeling: "Kontroll Midt",
    tags: [],
  },
  {
    id: "S-407",
    datoInnmeldt: "2025-11-05",
    kilde: "publikum",
    notat: "Publikumstips avsluttet",
    fødselsnummer: "40010799907",
    ytelser: ["Dagpenger", "Overgangsstønad"],
    status: "avsluttet",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-408",
    datoInnmeldt: "2025-12-01",
    kilde: "annet",
    notat: "Internkontrollsak avsluttet",
    fødselsnummer: "40010899908",
    ytelser: ["Sykepenger"],
    status: "avsluttet",
    seksjon: "Seksjon B",
    avdeling: "Kontroll Vest",
    tags: [],
  },
  // Henlagt (3 stk)
  {
    id: "S-501",
    datoInnmeldt: "2025-08-01",
    kilde: "telefon",
    notat: "Henlagt – utilstrekkelig grunnlag",
    fødselsnummer: "50010199901",
    ytelser: ["Dagpenger"],
    status: "henlagt",
    seksjon: "Seksjon A",
    avdeling: "Kontroll Øst",
    tags: [],
  },
  {
    id: "S-502",
    datoInnmeldt: "2025-09-15",
    kilde: "epost",
    notat: "Henlagt etter vurdering",
    fødselsnummer: "50010299902",
    ytelser: ["Sykepenger", "Foreldrepenger"],
    status: "henlagt",
    seksjon: "Seksjon C",
    avdeling: "Kontroll Nord",
    tags: [],
  },
  {
    id: "S-503",
    datoInnmeldt: "2025-10-20",
    kilde: "brev",
    notat: "Henlagt – feil mottaker",
    fødselsnummer: "50010399903",
    ytelser: ["Arbeidsavklaringspenger"],
    status: "henlagt",
    seksjon: "Seksjon D",
    avdeling: "Kontroll Sør",
    tags: [],
  },
];

export const mockStatistikkSaker: Sak[] = rådata.map((sak) => sakSchema.parse(sak));

/**
 * Simulerte avslutningsdatoer for avsluttede og henlagte saker.
 * I produksjon ville disse kommet fra historikk-hendelser.
 */
export const mockAvslutningsdatoer: Avslutningsdatoer = {
  "S-401": "2025-08-20", // 66 dager
  "S-402": "2025-08-15", // 45 dager
  "S-403": "2025-09-18", // 39 dager
  "S-404": "2025-12-10", // 100 dager
  "S-405": "2025-10-28", // 38 dager
  "S-406": "2025-10-18", // 8 dager
  "S-407": "2025-12-20", // 45 dager
  "S-408": "2025-12-22", // 21 dager
  "S-501": "2025-08-15", // 14 dager
  "S-502": "2025-10-01", // 16 dager
  "S-503": "2025-11-05", // 16 dager
};
